### ISSUE TITLE
bad_function_call in connection.cpp

### ISSUE THREAD

**Issue by hamadr** [romainletendart/geecxx#1]
_externalReadHandler(std::string(_buffer.data(), count));

if _externalReadHandler is not set the app crashes.

**Comment by romainletendart** [comment]
I think there are at least 2 ways of solving the issue.
Either we check the existence of the handler:

``` c++
if (_externalReadHandler) { _externalReadHandler(...); }
```

Or we set a default handler.
I'm in favor of the latter since it avoids doing a check each time we call the handler.

**Comment by romainletendart** [comment]
Fixed in 254a307.
