### ISSUE TITLE
Twitter page title problem

### ISSUE THREAD

**Issue by vaz-ar** [romainletendart/geecxx#4]
When processing a twitter link, the bot will return an URL in the title that point to a non existent page.

Example:

https://twitter.com/laquadrature/status/572754314600570880

```
La Quadrature du Net sur Twitter : "[fr][NextINpact] Au Parlement européen, un soupçon d'ACTA dans le rapport Svoboda - http://t.co/lna0DriFEl"; (https://twitter.com/laquadrature/status/572754314600570880)
```

**Comment by hamadr** [comment]
It seems that the bot does not handle &quot; as the link http://t.co/lna0DriFEl is correct but it is not displayed correctly in the title (" http://t.co/lna0DriFEl&quot;").
I would suggest to wait for the issue #3 to be resolved first.

**Comment by hamadr** [comment]
8b971f1
