### ISSUE TITLE
Filter out media links (images, sound, etc)

### ISSUE THREAD

**Issue by morukutsu** [romainletendart/geecxx#6]
When the bot parses an URL, it should ignore media links. 
More generally, the bot could ignore content which is not HTML and therefore, has no _title_ tag.
Filterting can be based on URL regexp or Content Type.

**Comment by romainletendart** [comment]
Links to media files are not yet filtered but displayed as "Untitled".
If we consider this as a valid behavior then this issue can be closed.

**Comment by romainletendart** [comment]
Fixed in:
596d25bc614464dc22c8d3903673c871c91ad8b4
