### ISSUE TITLE
Shorten URLs when showing page's title

### ISSUE THREAD

**Issue by jsilvestre** [romainletendart/geecxx#8]
So we don't have big URLs twice in the chat log.

Thank you very much!

**Comment by hamadr** [comment]
I don't agree with this feature.
There is a major issue with url shorteners : privacy.
Maybe we should only do it if the user said so.
What do you think @romainletendart?

**Comment by vaz-ar** [comment]
Why not integrate an url shortener in the bot ?

**Comment by jsilvestre** [comment]
@vaz-ar nailed it :)

**Comment by romainletendart** [comment]
URL shortening seems a good idea but I'm not really willing to make it part of the bot's features.
This would mean the bot should provide its own web server, have its own domain name, etc.

Instead, I would prefer to specify at runtime what URL shortening service to use (if any).

**Comment by romainletendart** [comment]
Do you consider the "title-only" display sufficient to close this issue?

**Comment by jsilvestre** [comment]
Yes sir.

**Comment by jsilvestre** [comment]
Thank you again <3
